---

#- name: Create user tower configuration
- template:
    src: "tower-cli.cfg.j2"
    dest: "{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: "yes"
  with_items: "{{ tcli_config }}"

# EOF
...
