---

- name: "debug: tower-cli"
  vars:
    msg: |
      ansible_os_family [{{ ansible_os_family }}]
      ansible_distribution [{{ ansible_distribution }}]
      ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
      ansible_distribution_version [{{ ansible_distribution_version }}]
      ansible_distribution_release [{{ ansible_distribution_release }}]
      ansible_python_version [{{ ansible_python_version }}]

      tcli_install [{{ tcli_install }}]
      tcli_debug_classified [{{ tcli_debug_classified }}]

      freebsd_install_method [{{ freebsd_install_method }}]
      freebsd_use_packages [{{ freebsd_use_packages }}]
      freebsd_install_retries [{{ freebsd_install_retries }}]
      freebsd_install_delay [{{ freebsd_install_delay }}]

      linux_install_retries [{{ linux_install_retries }}]
      linux_install_delay [{{ linux_install_delay }}]

      pip_install_retries [{{ pip_install_retries }}]
      pip_install_delay [{{ pip_install_delay }}]
      pip_extraagrs [{{ pip_extraagrs|default('UNDEFINED') }}]

      tcli_pip_install [{{ tcli_pip_install }}]
      tcli_pip_executable [{{ tcli_pip_executable }}]
      tcli_pip_requirements [{{ tcli_pip_requirements|default('UNDEFINED') }}]

      ansible_user_id [{{ ansible_user_id }}]

      tcli_owner [{{ tcli_owner }}]
      tcli_backup_conf [{{ tcli_backup_conf }}]

      tcli_packages
      {{ tcli_packages|to_nice_yaml }}
      tcli_links
      {{ tcli_links|to_nice_yaml }}

      tcli_config_scope [{{ tcli_config_scope }}]
      {% if tcli_debug_classified|bool %}
      tcli_config
      {{ tcli_config|to_yaml }}
      {% endif %}

  debug:
    msg: "{{ msg.split('\n')[:-1] }}"

# EOF
...
