---
# tasks for tower_cli

- import_tasks: vars.yml
  tags: [tcli_vars, always]

- import_tasks: debug.yml
  when: tcli_debug|bool
  tags: [tcli_debug, always]

- import_tasks: packages.yml
  when: tcli_install|bool
  tags: tcli_packages

- import_tasks: config.yml
  tags: tcli_config

# EOF
...
