---
# tasks for tower-cli

- name: Debug
  vars:
    msg: |
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
      tcli_install [ {{ tcli_install }} ]
      tcli_config [ {{ tcli_config }} ]
      tcli_owner [ {{ tcli_owner }} ]
      tcli_config_scope [ {{ tcli_config_scope }} ]
      tcli_config_file [ {{ tcli_config_file }} ]
      tcli_config_file_owner [ {{ tcli_config_file_owner }} ]
      tcli_config_file_group [ {{ tcli_config_file_group }} ]
      tcli_config_file_mode [ {{ tcli_config_file_mode }} ]
      tcli_config_host [ {{ tcli_config_host }} ]
      tcli_config_user [ {{ tcli_config_user }} ]
      tcli_config_proto [ {{ tcli_config_proto }} ]
      tcli_config_verifyssl [ {{ tcli_config_verifyssl }} ]
      tcli_config_passwd [ {{ tcli_config_passwd }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: tcli_debug|lower == "yes"
  tags:
    - tcli_debug
    - tcli_all

- name: Add {{ ansible_os_family }} specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - bsd_packages
    - tcli_vars
    - tcli_all

- import_tasks: packages.yml
  when: tcli_install|lower == "yes"
  tags:
    - bsd_packages
    - linux_packages
    - tcli_packages
    - tcli_all

- import_tasks: configure.yml
  when: tcli_config|lower == "yes"
  tags:
    - tcli_config
    - tcli_all

# EOF
...
