---
# tasks for tower-cli

- name: "Add {{ ansible_os_family }} specific variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [tcli_vars, always]

- name: Debug
  vars:
    msg: |
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]

      linux_install_retries [ {{ linux_install_retries }} ]
      linux_install_delay [ {{ linux_install_delay }} ]
      pip_executable [ {{ pip_executable }} ]
      pip_install_retries [ {{ pip_install_retries }} ]
      pip_install_delay [ {{ pip_install_delay }} ]

      tcli_install [ {{ tcli_install }} ]
      tcli_config_scope [ {{ tcli_config_scope }} ]
      tcli_config
      {{ tcli_config | to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: tcli_debug
  tags: [tcli_debug, always]

- import_tasks: packages.yml
  when: tcli_install
  tags: tcli_packages

- import_tasks: configure.yml
  tags: tcli_config

# EOF
...
