---

# packages -----------------------------------------------------------

# FreeBSD
- name: "packages: Install packages FreeBSD"
  block:
    - name: "packages: Install packages FreeBSD"
      pkgng:
        name: "{{ item.name }}"
      loop: "{{ tcli_packages }}"
      register: result
      until: result is succeeded
      retries: "{{ freebsd_install_retries }}"
      delay: "{{ freebsd_install_delay }}"
    - name: "packages: Debug FreeBSD packages"
      when: tcli_debug|bool
      debug:
        var: result
  when:
    - not tcli_pip_install
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"

- name: "packages: Install Ansible Lint ports FreeBSD"
  block:
    - name: "packages: Install Ansible Lint ports FreeBSD"
      portinstall:
        name: "{{ item.name }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ tcli_packages }}"
      register: result
      until: result is succeeded
      retries: "{{ freebsd_install_retries }}"
      delay: "{{ freebsd_install_delay }}"
    - name: "packages: Debug FreeBSD ports"
      when: tcli_debug|bool
      debug:
        var: result
  when:
    - not tcli_pip_install
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"

# Linux
- name: "packages: Install Ansible Lint packages Linux"
  block:
    - name: "packages: Install Ansible Lint packages Linux"
      package:
        name: "{{ item.name }}"
      loop: "{{ tcli_packages }}"
      register: result
      until: result is succeeded
      retries: "{{ linux_install_retries }}"
      delay: "{{ linux_install_delay }}"
    - name: "packages: Debug Linux"
      when: tcli_debug|bool
      debug:
        var: result
  when:
    - not tcli_pip_install
    - ansible_os_family == "RedHat" or ansible_os_family == "Debian"

# pip ----------------------------------------------------------------
- name: "packages: Test {{ tcli_pip_executable }} exists"
  when: tcli_pip_install
  block:
    - name: "packages: Stat {{ tcli_pip_executable }}"
      stat:
        path: "{{ tcli_pip_executable }}"
      register: result
    - name: "packages: Not exists {{ tcli_pip_executable }}"
      when: not result.stat.exists
      debug:
        msg: "[ERROR] {{ tcli_pip_executable }} does not exist. End of host."
    - name: "packages: Meta end host"
      when: not result.stat.exists
      meta: end_host

- name: "packages: Install Ansible Lint pip packages for {{ tcli_owner }}"
  when: tcli_pip_install
  become_user: "{{ tcli_owner }}"
  become: true
  changed_when: false  # Note 1.
  pip:
    name: "{{ item.name }}"
    executable: "{{ tcli_pip_executable }}"
    version: "{{ item.version|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    extra_args: "{{ pip_extraagrs|default(omit) }}"
  loop: "{{ tcli_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ pip_install_retries }}"
  delay: "{{ pip_install_delay }}"

- name: "packages: Debug pip packages"
  when:
    - tcli_pip_install
    - tcli_debug|bool
  debug:
    var: result

- name: "packages: Install Ansible Lint pip requirements for {{ tcli_owner }}"
  when:
    - tcli_pip_install
    - tcli_pip_requirements is defined
  become_user: "{{ tcli_owner }}"
  become: true
  changed_when: false  # Note 1.
  pip:
    requirements: "{{ tcli_pip_requirements }}"
    executable: "{{ tcli_pip_executable }}"
    extra_args: "{{ pip_extraagrs|default(omit) }}"
  register: result
  until: result is succeeded
  retries: "{{ pip_install_retries }}"
  delay: "{{ pip_install_delay }}"

- name: "packages: Debug pip requirements"
  when:
    - tcli_pip_install
    - tcli_debug|bool
  debug:
    var: result

# Note 1.
# The pip module isn't always idempotent #28952
# https://github.com/ansible/ansible/issues/28952

# EOF
...
