---

- debug: msg="ansible_os_family = {{ ansible_os_family }}"
  when: tcli_debug

# FreeBSD
- name: Install tower-cli FreeBSD
  pip:
    name: "{{ item }}"
  with_items: "{{ tcli_packages }}"
  when: ansible_os_family == "FreeBSD"

# Linux
- name: Install tower-cli Linux
  package:
    name: "{{ item }}"
  with_items: "{{ tcli_packages }}"
  when: (ansible_os_family == "RedHat") or
        (ansible_os_family == "Debian")
  
# EOF
...
