---

# FreeBSD
- name: Install tower-cli FreeBSD
  pip:
    name: "{{ item }}"
  loop: "{{ tcli_packages }}"
  when: ansible_os_family == "FreeBSD"

# Linux
- name: Install tower-cli Linux
  package:
    name: "{{ item }}"
  loop: "{{ tcli_packages }}"
  when: (ansible_os_family == "RedHat") or
        (ansible_os_family == "Debian")
  
# EOF
...
